### ISSUE TITLE
Clean up `net.peer.{ip,port,name}` attribute handling

### ISSUE THREAD

**Issue by akshayjshah** [bufbuild/connect-opentelemetry-go#48]
Let's follow up on https://github.com/bufbuild/connect-opentelemetry-go/pull/37#issuecomment-1358073237. We shouldn't use the `net.peer.ip` attribute at all, and servers and clients should both emit `net.peer.name` and `net.peer.port` by default. This is high cardinality, but matches the OTel specification.

As @joshcarp notes on #37, the `AttributeFilter` option introduced in #41 lets handlers strip the client port and IP from metrics to reduce cardinality. This seems likely to be a common request, so we should export an option like `WithLowerCardinality` that does this automatically.

**Comment by pkwarren** [comment]
I think we should aim for defaults that avoid high cardinality metrics (without configuring AttributeFilter or specifying an option).

https://opentelemetry.io/docs/reference/specification/metrics/semantic_conventions/rpc-metrics/ has some more details on this, in particular:
> To avoid high cardinality, implementations should prefer the most stable of net.peer.name or net.sock.peer.addr, depending on expected deployment profile. For many cloud applications, this is likely net.peer.name as names can be recycled even across re-instantiation of a server with a different ip.

For connect implementations, are we getting this value from the Host header?

**Comment by joshcarp** [comment]
> For connect implementations, are we getting this value from the Host header?

For connect implementations the peer.Addr() is used to populate net.peer.ip(net.peer.name in #50) and net.peer.port

I would lean towards leaving out the high cardinality attributes by default, because most people are going to set it up without any options and this will lead to the least headache. 

Either way the current implementation is the _most_ correct, 

I've got two commits on #50 
4184c0b that replaces `net.peer.ip` for `net.peer.name`, and
3a10d2c that adds a `WithLowerServerCardinality` option

**Comment by akshayjshah** [comment]
For now, I think we ought to follow the specification by default rather than inventing our own default behavior. In places where the spec is bad (like the cardinality problem we're discussing here), we should push users to make noise _on the otel spec_ and hope we can fix the spec before this library hits 1.0.

In cases where we know the spec is bad (like this one), we should also ship a hopefully-temporary escape hatch. Hopefully we'll be able to delete these escape hatches before we release a 1.0 of this library.

**Comment by joshcarp** [comment]
Closed by #50
