### ISSUE TITLE
The Span Status MUST be left unset for an OK gRPC status code, and set to Error for all others.

### ISSUE THREAD

**Issue by joshcarp** [bufbuild/connect-opentelemetry-go#51]
From the spec:

The [Span Status](https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/trace/api.md#set-status) MUST be left unset for an OK gRPC status code, and set to Error for all others.
https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/trace/semantic_conventions/rpc.md#grpc-status

Currently spanStatus is set to `codes.Ok` https://github.com/bufbuild/connect-opentelemetry-go/blob/6db18fe3823a852ca17875b68d739b035f26d028/interceptor.go#L277

**Comment by akshayjshah** [comment]
Huh, okay! How odd.

**Comment by joshcarp** [comment]
@akshayjshah what do you think about this?
Technically we don't *need* to follow the grpc spec exactly, and could diverge with this one.
@doriable also do you think this matters, should we stick to the `grpc` spec

Also notably this relates to a discussion on whether `status_code` or `error_code` is to be used in our attributes; 
- there is currently no concept of a `status_code` in connect (grpc has a `status_code` with 0 for `ok`). 
- if the attribute is `error_code` it would mean that there wouldn't be any indication that the call passed; `span_status` would be `Unset` and the `error_code` would only exist if there was an error with no `ok` status being set
