### ISSUE TITLE
Baggage propagation

### ISSUE THREAD

**Issue by joshcarp** [bufbuild/connect-opentelemetry-go#55]
Opentelemetry interceptors should propagate baggage, currently connect-opentelemetry-go does not

**Comment by akshayjshah** [comment]
Wait, this isn't handled _automatically_ as part of extracting and injecting spans? 😱

Sigh...yes, we definitely need to do this.

**Comment by joshcarp** [comment]
No, it's technically a different API; the idea being that it could carry different information that isn't just trace/metrics related.

**Comment by akshayjshah** [comment]
Yeah, I'm familiar with what baggage _is_; I'm just surprised that the
default APIs don't propagate spans and baggage together.

**Comment by joshcarp** [comment]
Okay, seems like you're correct; it is handled automatically, I think through `propagation.Baggage{}` as a `TextMapProcessor`

I don't think anything else needs to be done for this

**Comment by akshayjshah** [comment]
Can we add a few tests to make sure?
