### ISSUE TITLE
Trace context isn't propagated through the interceptor

### ISSUE THREAD

**Issue by DustinJSilk** [bufbuild/connect-opentelemetry-go#91]
Hello,

I'm trying to receive a trace which seems to be picked up by the otel package, however, its missed by the Interceptor which then provides a new trace ID to the context.

I've added this to my project before creating the interceptor:

```go
tc := propagation.NewCompositeTextMapPropagator(
  propagation.TraceContext{},
  propagation.Baggage{},
)
otel.SetTextMapPropagator(tc)
```

I'm passing a traceparent header and a tracestate header in my http request, from a Nodejs server.

The headers are recieved in my go server in the req.Headers interface. And when I step through the otel/propagation/trace_context.go `extract` function, the header is found and the correct IDs are returned but then not picked up by the interceptor.

Any guidance would be helpful! 
Thanks

**Comment by DustinJSilk** [comment]
I found the answer on Slack..

Adding `otelconnect.WithTrustRemote()` to the Interceptor solved the issue.
Hope this helps someone else.

Thanks

**Comment by akshayjshah** [comment]
Glad you found the right answer! Also, there's more documentation here: https://connect.build/docs/go/observability#configuration-for-internal-microservices

**Comment by alehechka** [comment]
@akshayjshah, I ran into this same issue and was stuck for a while trying to figure out when my internal traces weren't connected after sending to Honeycomb. Glad I finally found this issue, adding that to the Interceptor fixed it. 

I feel like that scenario is common enough, so is there any way that option could be called out/documented on the README here in this repo?

**Comment by akshayjshah** [comment]
Definitely!

**Comment by akshayjshah** [comment]
@alehechka and @DustinJSilk - updated the README in this repo to include documentation on `WithTrustRemote`, and also to link more obviously to the docs on https://connect.build. Thank you for bearing with us!
