### ISSUE TITLE
Problems updating dependencies

### ISSUE THREAD

**Issue by nomad-software** [bufbuild/connect-opentelemetry-go#99]
There seems to be a problem when trying the following command in projects that import this library. This is the case for all projects I've tried so far.

```
go get -u ./...

github.com/<user>/<project> imports
	github.com/bufbuild/connect-opentelemetry-go imports
	go.opentelemetry.io/otel/metric/global: cannot find module providing package go.opentelemetry.io/otel/metric/global
```

The issue seems to be that the upstream opentelemetry.io library moved the `metric` directory in an update and then moved it back in another. Creating a conflict somewhere.

Can you please take a look and maybe update the dependencies of this library so it pulls in the correct sdk version please?

**Comment by thesiti92** [comment]
installing the lib is also broken for me

**Comment by joshcarp** [comment]
It seems like the `global` package is removed in a release candidate [v1.15.0-rc.2](https://github.com/open-telemetry/opentelemetry-go/releases/tag/v1.15.0-rc.2)

I don't think go mod would update to this version automatically, and it breaks when I run `go get go.opentelemetry.io/otel/metric@v1.15.0-rc.2`. 
Because this is a release candidate the connect-opentelemetry-go library will not depend on it until it's released

**Comment by nomad-software** [comment]
So what's the solution? Any project that imports this library has issues updating dependencies.

This library has a version of [v0.1.0](https://github.com/bufbuild/connect-opentelemetry-go/releases/tag/v0.1.0) so it's beta itself, so why not use the release candidate if it at least fixes this library?

**Comment by joshcarp** [comment]
Hey @nomad-software, are you using vendor?

**Comment by joshcarp** [comment]
I will be releasing a minor version that depends on the opentelemetry rc version so that should fix this problem

**Comment by nomad-software** [comment]
> Hey @nomad-software, are you using vendor?

Hi, yes I am vendor'ing dependencies.
I've removed the `vendor` folder and tried again to update and get the same error.

**Comment by nomad-software** [comment]
> I will be releasing a minor version that depends on the opentelemetry rc version so that should fix this problem

Looks like a new version of opentelemetry has just dropped:

https://github.com/open-telemetry/opentelemetry-go/releases/tag/v1.15.0

**Comment by Tochemey** [comment]
Yeah a quick update is needed here because the otel metric api has changed a bit and it broke my project when using connect-otel

**Comment by nomad-software** [comment]
Looks like another opentelemetry update has been released addressing build failures:

https://github.com/open-telemetry/opentelemetry-go/releases/tag/v1.15.1

**Comment by joshcarp** [comment]
I've released https://github.com/bufbuild/connect-opentelemetry-go/releases/tag/v0.2.0 which depends on otel-go v1.15.1/v0.38.1

**Comment by joshcarp** [comment]
Closing this issue as OpenTelemetry-go is now stable and the latest release https://github.com/bufbuild/connect-opentelemetry-go/releases/tag/v0.3.0 depends on it.
